### ISSUE TITLE
Target operations

### ISSUE THREAD

**Issue by gdevenyi** [CobraLab/minc-bpipe-library#1]
- [x] n3correct (nu_correct)
- [x] n4correct (N4BiasFieldCorrect)
- [x] denoise (volume_denoise.pl)
- [ ] average
- [x] beast (beast_bpipe)
- [x] deface
- [x] normalize minc_nuyl
- [x] normalize - volume_pol
- [x] normalize - dumb mode (scale and throw away top and bottom 1%)
- [x] cut-neck
- [x] linear registration (mincANTS)
- [ ] nonlinear registration

Current understanding of "best" order of operations is:
denoise -> n3/n4correct -> normalize

**Comment by raihaan** [comment]
its late, so i might be missing it - but looks like resampling both masks and extracted brains to native space is missing from beast stages, we should add.

i believe 

```
mincresample -like nativeimage.mnc -transformation MNI_register_inverse.xfm *beastmask.mnc nativemask.mnc 
```
should do the trick

**Comment by gdevenyi** [comment]
What exactly are the relevant outputs for beast, the mask and brain in MNI space or the mask and brain in native space?

**Comment by raihaan** [comment]
I'd say the native mask and native brain are the final outputs - this was the step before extraction in our original BEaST how to:

https://github.com/CobraLab/documentation/wiki/How-to-run-BEaST
