### ISSUE TITLE
Implement VBM stages

### ISSUE THREAD

**Issue by gdevenyi** [CobraLab/minc-bpipe-library#16]
minc-tookit has a VBM toolchain, consists of

- register brain
- extract brain
- classify
- smooth

Classify brain matter according to 152_09c model:
```
classify_clean -tagdir /opt/quarantine/resources/mni_icbm152_nlin_sym_09c_minc2 \
-tagfile mni_icbm152_t1_tal_nlin_sym_09c_ntags_1000_prob_90_nobg.tag \
-bgtagfile mni_icbm152_t1_tal_nlin_sym_09c_ntags_1000_bg.tag -clobber \
-mask brainmask -mask_source -clean_tags \
$input $ouput
```
```
smooth_mask -binvalue 1 -fwhm 10 classified_brain.mnc smooth_CSF.mnc
smooth_mask -binvalue 2 -fwhm 10 classified_brain.mnc smooth_grey.mnc
smooth_mask -binvalue 3 -fwhm 10 classified_brain.mnc smooth_white.mnc
```

**Comment by mallarchak** [comment]
Definitely - but just remember that this is really an old way of doing
VBM.  There are far more sophisticated ways in other tool boxes.  One way
to do this would be to modulate using the Jacobians (and applying nl xfms
of course).

**Comment by gdevenyi** [comment]
Old school minc-toolkit based VBM implemented.

Other implementation suggestions welcome.
